# Neo4j Migration Docker Compose Configuration
# 包含所有必要服务，支持双数据库模式

services:
  # ========== 应用服务 ==========
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prod
    image: literature_parser_backend:${LITERATURE_PARSER_BACKEND_VERSION:-latest}
    restart: always
    env_file:
      - .env
    environment:
      # MongoDB配置（容器内使用服务名）
      - LITERATURE_PARSER_BACKEND_DB_HOST=db
      # Neo4j配置
      - LITERATURE_PARSER_BACKEND_NEO4J_URI=bolt://neo4j:7687
      - LITERATURE_PARSER_BACKEND_NEO4J_USERNAME=neo4j
      - LITERATURE_PARSER_BACKEND_NEO4J_PASSWORD=literature_parser_neo4j
      # Elasticsearch配置
      - LITERATURE_PARSER_BACKEND_ES_HOST=elasticsearch
      - LITERATURE_PARSER_BACKEND_ES_PORT=9200
      - LITERATURE_PARSER_BACKEND_ES_USERNAME=elastic
      - LITERATURE_PARSER_BACKEND_ES_PASSWORD=literature_parser_elastic
      # 迁移模式配置
      - LITERATURE_PARSER_BACKEND_DB_MODE=dual
    command: poetry run python -m literature_parser_backend
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      neo4j:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    networks:
      - literature_parser_network
    ports:
      - "8000:8000"

  worker:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prod
    image: literature_parser_backend:${LITERATURE_PARSER_BACKEND_VERSION:-latest}
    restart: always
    env_file:
      - .env
    environment:
      # MongoDB配置（容器内使用服务名）
      - LITERATURE_PARSER_BACKEND_DB_HOST=db
      # 与api相同的配置
      - LITERATURE_PARSER_BACKEND_NEO4J_URI=bolt://neo4j:7687
      - LITERATURE_PARSER_BACKEND_NEO4J_USERNAME=neo4j
      - LITERATURE_PARSER_BACKEND_NEO4J_PASSWORD=literature_parser_neo4j
      - LITERATURE_PARSER_BACKEND_ES_HOST=elasticsearch
      - LITERATURE_PARSER_BACKEND_ES_PORT=9200
      - LITERATURE_PARSER_BACKEND_ES_USERNAME=elastic
      - LITERATURE_PARSER_BACKEND_ES_PASSWORD=literature_parser_elastic
      - LITERATURE_PARSER_BACKEND_DB_MODE=dual
    command: poetry run celery -A literature_parser_backend.worker.celery_app worker --loglevel=info --concurrency=8 --queues=literature
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      grobid:
        condition: service_started
      neo4j:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./debug_pdfs:/tmp/debug_pdfs
    networks:
      - literature_parser_network

  # ========== 新增服务 ==========
  neo4j:
    image: neo4j:5.15-community
    container_name: literature_parser_neo4j
    restart: always
    environment:
      # 认证配置
      - NEO4J_AUTH=neo4j/literature_parser_neo4j
      
      # 性能配置
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_memory_pagecache_size=1G
      
      # APOC插件支持（图算法）
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      
      # 安全配置
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_allow__csv__import__from__file__urls=true
      
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - literature_parser_neo4j_data:/data
      - literature_parser_neo4j_logs:/logs
      - literature_parser_neo4j_import:/var/lib/neo4j/import
      - literature_parser_neo4j_plugins:/plugins
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "literature_parser_neo4j", "RETURN 1"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s
    networks:
      - literature_parser_network

  elasticsearch:
    image: elasticsearch:8.11.0
    container_name: literature_parser_elasticsearch
    restart: always
    environment:
      # 集群配置
      - node.name=literature_parser_es_node
      - cluster.name=literature_parser_es_cluster
      - discovery.type=single-node
      
      # 内存配置
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - bootstrap.memory_lock=true
      
      # 安全配置
      - ELASTIC_PASSWORD=literature_parser_elastic
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - literature_parser_elasticsearch_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-u", "elastic:literature_parser_elastic", "-f", "http://localhost:9200/_cluster/health"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s
    networks:
      - literature_parser_network

  # ========== 原有必要服务 ==========
  db:
    image: mongo:7.0
    hostname: literature_parser_backend-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "literature_parser_backend"
      MONGO_INITDB_ROOT_PASSWORD: "literature_parser_backend"
    command: "mongod"
    volumes:
      - literature_parser_backend-db-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://literature_parser_backend:literature_parser_backend@localhost:27017/literature_parser?authSource=admin --quiet
      interval: 10s
      timeout: 5s
      retries: 40
    networks:
      - literature_parser_network
    ports:
      - "27017:27017"

  redis:
    image: redis:7-alpine
    hostname: literature_parser_backend-redis
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - literature_parser_backend-redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - literature_parser_network
    ports:
      - "6379:6379"

  grobid:
    image: lfoppiano/grobid:0.8.2
    hostname: literature_parser_backend-grobid
    restart: always
    environment:
      JAVA_OPTS: "-Xmx2g"
    healthcheck:
      test: ["CMD", "timeout", "5", "bash", "-c", "</dev/tcp/localhost/8070"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - literature_parser_network
    ports:
      - "8070:8070"

networks:
  literature_parser_network:
    driver: bridge

volumes:
  # 原有卷保持
  literature_parser_backend-db-data:
  literature_parser_backend-redis-data:
  
  # Neo4j新增卷
  literature_parser_neo4j_data:
    driver: local
  literature_parser_neo4j_logs:
    driver: local  
  literature_parser_neo4j_import:
    driver: local
  literature_parser_neo4j_plugins:
    driver: local
    
  # Elasticsearch新增卷
  literature_parser_elasticsearch_data:
    driver: local
