services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    # Override command for development with auto-reload
    command: poetry run uvicorn literature_parser_backend.web.application:get_app --factory --host 0.0.0.0 --port 8000 --reload

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    # Override command for development with auto-reload
    command: poetry run celery -A literature_parser_backend.worker.celery_app worker --loglevel=debug --concurrency=1 --queues=literature
    dns: 8.8.8.8
